-- MySQL Script generated by MySQL Workbench
-- 11/02/16 16:29:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vendee
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `vendee`;

-- -----------------------------------------------------
-- Schema vendee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vendee` DEFAULT CHARACTER SET utf8 ;
USE `vendee` ;

-- -----------------------------------------------------
-- Table `vendee`.`personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendee`.`personnes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL,
  `prenom` VARCHAR(255) NULL,
  `sexe` CHAR(1) NULL,
  `naissance` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendee`.`type_acte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendee`.`types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendee`.`lieu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendee`.`lieus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL,
  `departement` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendee`.`acte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendee`.`actes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numVue` VARCHAR(255) NULL,
  `id_lieu` INT NULL,
  `id_type_acte` INT NOT NULL,
  `id_personne` INT NULL,
  `id_personne_marie` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ACTE_LIEU_idx` (`id_lieu` ASC),
  INDEX `fk_ACTE_TYPE_ACTE1_idx` (`id_type_acte` ASC),
  INDEX `fk_acte_personne1_idx` (`id_personne` ASC),
  INDEX `fk_acte_personne2_idx` (`id_personne_marie` ASC),
  CONSTRAINT `fk_ACTE_LIEU`
    FOREIGN KEY (`id_lieu`)
    REFERENCES `vendee`.`lieus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ACTE_TYPE_ACTE1`
    FOREIGN KEY (`id_type_acte`)
    REFERENCES `vendee`.`types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acte_personne1`
    FOREIGN KEY (`id_personne`)
    REFERENCES `vendee`.`personnes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acte_personne2`
    FOREIGN KEY (`id_personne_marie`)
    REFERENCES `vendee`.`personnes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendee`.`parent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendee`.`enfants` (
  `id_enfant` INT NULL,
  `id_parent` INT NULL,
  INDEX `fk_parent_personne1_idx` (`id_enfant` ASC),
  INDEX `fk_parent_personne2_idx` (`id_parent` ASC),
  CONSTRAINT `fk_parent_personne1`
    FOREIGN KEY (`id_enfant`)
    REFERENCES `vendee`.`personnes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enfants_personne2`
    FOREIGN KEY (`id_parent`)
    REFERENCES `vendee`.`personnes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendee`.`marie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendee`.`maries` (
  `id_epoux` INT NULL,
  `id_epouse` INT NULL,
  INDEX `fk_marie_personne1_idx` (`id_epoux` ASC),
  INDEX `fk_marie_personne2_idx` (`id_epouse` ASC),
  CONSTRAINT `fk_marie_personne1`
    FOREIGN KEY (`id_epoux`)
    REFERENCES `vendee`.`personnes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_marie_personne2`
    FOREIGN KEY (`id_epouse`)
    REFERENCES `vendee`.`personnes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `vendee`.`raw_mariage` (
  `id` VARCHAR(255),
  `typeActe` VARCHAR(255),
  `epoux` VARCHAR(255),
  `prenomEpoux` VARCHAR(255),
  `prenomPereEpoux` VARCHAR(255),
  `nomMereEpoux` VARCHAR(255),
  `prenomMereEpoux` VARCHAR(255),
  `epouse` VARCHAR(255),
  `prenomEpouse` VARCHAR(255),
  `prenomPereEpouse` VARCHAR(255),
  `nomMereEpouse` VARCHAR(255),
  `prenomMereEpouse` VARCHAR(255),
  `lieu` VARCHAR(255),
  `dept` VARCHAR(255),
  `dates` VARCHAR(255),
  `numVue` VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS `vendee`.`raw_deces` (
  `id` VARCHAR(255),
  `typeActe` VARCHAR(255),
  `nom` VARCHAR(255),
  `prenom` VARCHAR(255),
  `age` VARCHAR(255),
  `nomPere` VARCHAR(255),
  `prenomPere` VARCHAR(255),
  `nomMere` VARCHAR(255),
  `prenomMere` VARCHAR(255),
  `lieu` VARCHAR(255),
  `dept` VARCHAR(255),
  `dateNaissance` VARCHAR(255),
  `numVue` VARCHAR(255)
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

LOAD DATA LOCAL INFILE "X:/datamining-vendee/resources/raw/deces_L3.csv"
INTO TABLE `vendee`.`raw_deces`
FIELDS TERMINATED BY ',' ENCLOSED BY '' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE "X:/datamining-vendee/resources/raw/mariages_L3.csv"
INTO TABLE `vendee`.`raw_mariage`
FIELDS TERMINATED BY ',' ENCLOSED BY '' LINES TERMINATED BY '\n';
